version: "3"

services:
  app:
    build: docker/php
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_enable=On remote_connect_back=On"

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app

  mailcatcher:
      image: schickling/mailcatcher:latest
      ports:
        - 1080:1080

  db:
    image: mysql:8
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2-starter-kit
      MYSQL_USER: ysk_dbu
      MYSQL_PASSWORD: ysk_pass
