<?php

use yii\db\Migration;

/**
 * Handles the creation of table `country`.
 */
class m171211_144129_create_country_table extends Migration
{
    /**
     * @inheritdoc
     */
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%country}}', [
            'id' => $this->primaryKey()->unsigned(),
            'name' => $this->string(255),
            'sortname' => $this->string(32),
            'country_capital' => $this->string(255),
            'phonecode' => $this->string(32),
            'currency_code' => $this->string(64),
            'currency_symbol' => $this->string(64),
            'country_flag' => $this->string(512),
        ], $tableOptions);

        $this->batchInsert('{{%country}}', [
            'name', 'sortname', 'country_capital', 'phonecode', 'currency_code', 'currency_symbol', 'country_flag'],
            [
                ['Afghanistan', 'AF', 'Kabul', 93, 'AFN', '؋', 'https://restcountries.eu/data/afg.svg'],
                ['Åland Islands', 'AX', 'Mariehamn', 358, 'EUR', '€', 'https://restcountries.eu/data/ala.svg'],
                ['Albania', 'AL', 'Tirana', 355, 'ALL', 'L', 'https://restcountries.eu/data/alb.svg'],
                ['Algeria', 'DZ', 'Algiers', 213, 'DZD', 'د.ج', 'https://restcountries.eu/data/dza.svg'],
                ['American Samoa', 'AS', 'Pago Pago', 1684, 'USD', '$', 'https://restcountries.eu/data/asm.svg'],
                ['Andorra', 'AD', 'Andorra la Vella', 376, 'EUR', '€', 'https://restcountries.eu/data/and.svg'],
                ['Angola', 'AO', 'Luanda', 244, 'AOA', 'Kz', 'https://restcountries.eu/data/ago.svg'],
                ['Anguilla', 'AI', 'The Valley', 1264, 'XCD', '$', 'https://restcountries.eu/data/aia.svg'],
                ['Antarctica', 'AQ', '', 672, 'AUD', '$', 'https://restcountries.eu/data/ata.svg'],
                ['Antigua and Barbuda', 'AG', 'Saint John\'s', 1268, 'XCD', '$', 'https://restcountries.eu/data/atg.svg'],
                ['Argentina', 'AR', 'Buenos Aires', 54, 'ARS', '$', 'https://restcountries.eu/data/arg.svg'],
                ['Armenia', 'AM', 'Yerevan', 374, 'AMD', NULL, 'https://restcountries.eu/data/arm.svg'],
                ['Aruba', 'AW', 'Oranjestad', 297, 'AWG', 'ƒ', 'https://restcountries.eu/data/abw.svg'],
                ['Australia', 'AU', 'Canberra', 61, 'AUD', '$', 'https://restcountries.eu/data/aus.svg'],
                ['Austria', 'AT', 'Vienna', 43, 'EUR', '€', 'https://restcountries.eu/data/aut.svg'],
                ['Azerbaijan', 'AZ', 'Baku', 994, 'AZN', NULL, 'https://restcountries.eu/data/aze.svg'],
                ['Bahamas', 'BS', 'Nassau', 1242, 'BSD', '$', 'https://restcountries.eu/data/bhs.svg'],
                ['Bahrain', 'BH', 'Manama', 973, 'BHD', '.د.ب', 'https://restcountries.eu/data/bhr.svg'],
                ['Bangladesh', 'BD', 'Dhaka', 880, 'BDT', '৳', 'https://restcountries.eu/data/bgd.svg'],
                ['Barbados', 'BB', 'Bridgetown', 1246, 'BBD', '$', 'https://restcountries.eu/data/brb.svg'],
                ['Belarus', 'BY', 'Minsk', 375, 'BYN', 'Br', 'https://restcountries.eu/data/blr.svg'],
                ['Belgium', 'BE', 'Brussels', 32, 'EUR', '€', 'https://restcountries.eu/data/bel.svg'],
                ['Belize', 'BZ', 'Belmopan', 501, 'BZD', '$', 'https://restcountries.eu/data/blz.svg'],
                ['Benin', 'BJ', 'Porto-Novo', 229, 'XOF', 'Fr', 'https://restcountries.eu/data/ben.svg'],
                ['Bermuda', 'BM', 'Hamilton', 1441, 'BMD', '$', 'https://restcountries.eu/data/bmu.svg'],
                ['Bhutan', 'BT', 'Thimphu', 975, 'BTN', 'Nu.', 'https://restcountries.eu/data/btn.svg'],
                ['Bolivia', 'BO', 'Sucre', 591, 'BOB', 'Bs.', 'https://restcountries.eu/data/bol.svg'],
                ['Bonaire', 'BQ', 'Kralendijk', 5997, 'USD', '$', 'https://restcountries.eu/data/bes.svg'],
                ['Bosnia and Herzegovina', 'BA', 'Sarajevo', 387, 'BAM', NULL, 'https://restcountries.eu/data/bih.svg'],
                ['Botswana', 'BW', 'Gaborone', 267, 'BWP', 'P', 'https://restcountries.eu/data/bwa.svg'],
                ['Bouvet Island', 'BV', '', NULL, 'NOK', 'kr', 'https://restcountries.eu/data/bvt.svg'],
                ['Brazil', 'BR', 'Brasília', 55, 'BRL', 'R$', 'https://restcountries.eu/data/bra.svg'],
                ['British Indian Ocean Territory', 'IO', 'Diego Garcia', 246, 'USD', '$', 'https://restcountries.eu/data/iot.svg'],
                ['United States Minor Outlying Islands', 'UM', '', NULL, 'USD', '$', 'https://restcountries.eu/data/umi.svg'],
                ['Virgin Islands (British)', 'VG', 'Road Town', 1284, NULL, '$', 'https://restcountries.eu/data/vgb.svg'],
                ['Virgin Islands (U.S.)', 'VI', 'Charlotte Amalie', 1, 'USD', '$', 'https://restcountries.eu/data/vir.svg'],
                ['Brunei Darussalam', 'BN', 'Bandar Seri Begawan', 673, 'BND', '$', 'https://restcountries.eu/data/brn.svg'],
                ['Bulgaria', 'BG', 'Sofia', 359, 'BGN', 'лв', 'https://restcountries.eu/data/bgr.svg'],
                ['Burkina Faso', 'BF', 'Ouagadougou', 226, 'XOF', 'Fr', 'https://restcountries.eu/data/bfa.svg'],
                ['Burundi', 'BI', 'Bujumbura', 257, 'BIF', 'Fr', 'https://restcountries.eu/data/bdi.svg'],
                ['Cambodia', 'KH', 'Phnom Penh', 855, 'KHR', '៛', 'https://restcountries.eu/data/khm.svg'],
                ['Cameroon', 'CM', 'Yaoundé', 237, 'XAF', 'Fr', 'https://restcountries.eu/data/cmr.svg'],
                ['Canada', 'CA', 'Ottawa', 1, 'CAD', '$', 'https://restcountries.eu/data/can.svg'],
                ['Cabo Verde', 'CV', 'Praia', 238, 'CVE', 'Esc', 'https://restcountries.eu/data/cpv.svg'],
                ['Cayman Islands', 'KY', 'George Town', 1345, 'KYD', '$', 'https://restcountries.eu/data/cym.svg'],
                ['Central African', 'CF', 'Bangui', 236, 'XAF', 'Fr', 'https://restcountries.eu/data/caf.svg'],
                ['Chad', 'TD', 'N\'Djamena', 235, 'XAF', 'Fr', 'https://restcountries.eu/data/tcd.svg'],
                ['Chile', 'CL', 'Santiago', 56, 'CLP', '$', 'https://restcountries.eu/data/chl.svg'],
                ['China', 'CN', 'Beijing', 86, 'CNY', '¥', 'https://restcountries.eu/data/chn.svg'],
                ['Christmas Island', 'CX', 'Flying Fish Cove', 61, 'AUD', '$', 'https://restcountries.eu/data/cxr.svg'],
                ['Cocos', 'CC', 'West Island', 61, 'AUD', '$', 'https://restcountries.eu/data/cck.svg'],
                ['Colombia', 'CO', 'Bogotá', 57, 'COP', '$', 'https://restcountries.eu/data/col.svg'],
                ['Comoros', 'KM', 'Moroni', 269, 'KMF', 'Fr', 'https://restcountries.eu/data/com.svg'],
                ['Congo', 'CG', 'Brazzaville', 242, 'XAF', 'Fr', 'https://restcountries.eu/data/cog.svg'],
                ['Congo', 'CD', 'Kinshasa', 243, 'CDF', 'Fr', 'https://restcountries.eu/data/cod.svg'],
                ['Cook Islands', 'CK', 'Avarua', 682, 'NZD', '$', 'https://restcountries.eu/data/cok.svg'],
                ['Costa Rica', 'CR', 'San José', 506, 'CRC', '₡', 'https://restcountries.eu/data/cri.svg'],
                ['Croatia', 'HR', 'Zagreb', 385, 'HRK', 'kn', 'https://restcountries.eu/data/hrv.svg'],
                ['Cuba', 'CU', 'Havana', 53, 'CUC', '$', 'https://restcountries.eu/data/cub.svg'],
                ['Curaçao', 'CW', 'Willemstad', 599, 'ANG', 'ƒ', 'https://restcountries.eu/data/cuw.svg'],
                ['Cyprus', 'CY', 'Nicosia', 357, 'EUR', '€', 'https://restcountries.eu/data/cyp.svg'],
                ['Czech Republic', 'CZ', 'Prague', 420, 'CZK', 'K�?', 'https://restcountries.eu/data/cze.svg'],
                ['Denmark', 'DK', 'Copenhagen', 45, 'DKK', 'kr', 'https://restcountries.eu/data/dnk.svg'],
                ['Djibouti', 'DJ', 'Djibouti', 253, 'DJF', 'Fr', 'https://restcountries.eu/data/dji.svg'],
                ['Dominica', 'DM', 'Roseau', 1767, 'XCD', '$', 'https://restcountries.eu/data/dma.svg'],
                ['Dominican Republic', 'DO', 'Santo Domingo', 1809, 'DOP', '$', 'https://restcountries.eu/data/dom.svg'],
                ['Ecuador', 'EC', 'Quito', 593, 'USD', '$', 'https://restcountries.eu/data/ecu.svg'],
                ['Egypt', 'EG', 'Cairo', 20, 'EGP', '£', 'https://restcountries.eu/data/egy.svg'],
                ['El Salvador', 'SV', 'San Salvador', 503, 'USD', '$', 'https://restcountries.eu/data/slv.svg'],
                ['Equatorial Guinea', 'GQ', 'Malabo', 240, 'XAF', 'Fr', 'https://restcountries.eu/data/gnq.svg'],
                ['Eritrea', 'ER', 'Asmara', 291, 'ERN', 'Nfk', 'https://restcountries.eu/data/eri.svg'],
                ['Estonia', 'EE', 'Tallinn', 372, 'EUR', '€', 'https://restcountries.eu/data/est.svg'],
                ['Ethiopia', 'ET', 'Addis Ababa', 251, 'ETB', 'Br', 'https://restcountries.eu/data/eth.svg'],
                ['Falkland Islands', 'FK', 'Stanley', 500, 'FKP', '£', 'https://restcountries.eu/data/flk.svg'],
                ['Faroe Islands', 'FO', 'Tórshavn', 298, 'DKK', 'kr', 'https://restcountries.eu/data/fro.svg'],
                ['Fiji', 'FJ', 'Suva', 679, 'FJD', '$', 'https://restcountries.eu/data/fji.svg'],
                ['Finland', 'FI', 'Helsinki', 358, 'EUR', '€', 'https://restcountries.eu/data/fin.svg'],
                ['France', 'FR', 'Paris', 33, 'EUR', '€', 'https://restcountries.eu/data/fra.svg'],
                ['French Guiana', 'GF', 'Cayenne', 594, 'EUR', '€', 'https://restcountries.eu/data/guf.svg'],
                ['French Polynesia', 'PF', 'Papeetē', 689, 'XPF', 'Fr', 'https://restcountries.eu/data/pyf.svg'],
                ['French Southern Territories', 'TF', 'Port-aux-Français', NULL, 'EUR', '€', 'https://restcountries.eu/data/atf.svg'],
                ['Gabon', 'GA', 'Libreville', 241, 'XAF', 'Fr', 'https://restcountries.eu/data/gab.svg'],
                ['Gambia', 'GM', 'Banjul', 220, 'GMD', 'D', 'https://restcountries.eu/data/gmb.svg'],
                ['Georgia', 'GE', 'Tbilisi', 995, 'GEL', 'ლ', 'https://restcountries.eu/data/geo.svg'],
                ['Germany', 'DE', 'Berlin', 49, 'EUR', '€', 'https://restcountries.eu/data/deu.svg'],
                ['Ghana', 'GH', 'Accra', 233, 'GHS', '₵', 'https://restcountries.eu/data/gha.svg'],
                ['Gibraltar', 'GI', 'Gibraltar', 350, 'GIP', '£', 'https://restcountries.eu/data/gib.svg'],
                ['Greece', 'GR', 'Athens', 30, 'EUR', '€', 'https://restcountries.eu/data/grc.svg'],
                ['Greenland', 'GL', 'Nuuk', 299, 'DKK', 'kr', 'https://restcountries.eu/data/grl.svg'],
                ['Grenada', 'GD', 'St. George\'s', 1473, 'XCD', '$', 'https://restcountries.eu/data/grd.svg'],
                ['Guadeloupe', 'GP', 'Basse-Terre', 590, 'EUR', '€', 'https://restcountries.eu/data/glp.svg'],
                ['Guam', 'GU', 'Hagåtña', 1671, 'USD', '$', 'https://restcountries.eu/data/gum.svg'],
                ['Guatemala', 'GT', 'Guatemala City', 502, 'GTQ', 'Q', 'https://restcountries.eu/data/gtm.svg'],
                ['Guernsey', 'GG', 'St. Peter Port', 44, 'GBP', '£', 'https://restcountries.eu/data/ggy.svg'],
                ['Guinea', 'GN', 'Conakry', 224, 'GNF', 'Fr', 'https://restcountries.eu/data/gin.svg'],
                ['Guinea-Bissau', 'GW', 'Bissau', 245, 'XOF', 'Fr', 'https://restcountries.eu/data/gnb.svg'],
                ['Guyana', 'GY', 'Georgetown', 592, 'GYD', '$', 'https://restcountries.eu/data/guy.svg'],
                ['Haiti', 'HT', 'Port-au-Prince', 509, 'HTG', 'G', 'https://restcountries.eu/data/hti.svg'],
                ['Heard Island and McDonald Islands', 'HM', '', NULL, 'AUD', '$', 'https://restcountries.eu/data/hmd.svg'],
                ['Holy See', 'VA', 'Rome', 379, 'EUR', '€', 'https://restcountries.eu/data/vat.svg'],
                ['Honduras', 'HN', 'Tegucigalpa', 504, 'HNL', 'L', 'https://restcountries.eu/data/hnd.svg'],
                ['Hong Kong', 'HK', 'City of Victoria', 852, 'HKD', '$', 'https://restcountries.eu/data/hkg.svg'],
                ['Hungary', 'HU', 'Budapest', 36, 'HUF', 'Ft', 'https://restcountries.eu/data/hun.svg'],
                ['Iceland', 'IS', 'Reykjavík', 354, 'ISK', 'kr', 'https://restcountries.eu/data/isl.svg'],
                ['India', 'IN', 'New Delhi', 91, 'INR', '₹', 'https://restcountries.eu/data/ind.svg'],
                ['Indonesia', 'ID', 'Jakarta', 62, 'IDR', 'Rp', 'https://restcountries.eu/data/idn.svg'],
                ['Côte d\'Ivoire', 'CI', 'Yamoussoukro', 225, 'XOF', 'Fr', 'https://restcountries.eu/data/civ.svg'],
                ['Iran (Islamic Republic of)', 'IR', 'Tehran', 98, 'IRR', '﷼', 'https://restcountries.eu/data/irn.svg'],
                ['Iraq', 'IQ', 'Baghdad', 964, 'IQD', 'ع.د', 'https://restcountries.eu/data/irq.svg'],
                ['Ireland', 'IE', 'Dublin', 353, 'EUR', '€', 'https://restcountries.eu/data/irl.svg'],
                ['Isle of Man', 'IM', 'Douglas', 44, 'GBP', '£', 'https://restcountries.eu/data/imn.svg'],
                ['Israel', 'IL', 'Jerusalem', 972, 'ILS', '₪', 'https://restcountries.eu/data/isr.svg'],
                ['Italy', 'IT', 'Rome', 39, 'EUR', '€', 'https://restcountries.eu/data/ita.svg'],
                ['Jamaica', 'JM', 'Kingston', 1876, 'JMD', '$', 'https://restcountries.eu/data/jam.svg'],
                ['Japan', 'JP', 'Tokyo', 81, 'JPY', '¥', 'https://restcountries.eu/data/jpn.svg'],
                ['Jersey', 'JE', 'Saint Helier', 44, 'GBP', '£', 'https://restcountries.eu/data/jey.svg'],
                ['Jordan', 'JO', 'Amman', 962, 'JOD', 'د.ا', 'https://restcountries.eu/data/jor.svg'],
                ['Kazakhstan', 'KZ', 'Astana', 76, 'KZT', NULL, 'https://restcountries.eu/data/kaz.svg'],
                ['Kenya', 'KE', 'Nairobi', 254, 'KES', 'Sh', 'https://restcountries.eu/data/ken.svg'],
                ['Kiribati', 'KI', 'South Tarawa', 686, 'AUD', '$', 'https://restcountries.eu/data/kir.svg'],
                ['Kuwait', 'KW', 'Kuwait City', 965, 'KWD', 'د.ك', 'https://restcountries.eu/data/kwt.svg'],
                ['Kyrgyzstan', 'KG', 'Bishkek', 996, 'KGS', '�?', 'https://restcountries.eu/data/kgz.svg'],
                ['Lao People\'s Democratic Republic', 'LA', 'Vientiane', 856, 'LAK', '₭', 'https://restcountries.eu/data/lao.svg'],
                ['Latvia', 'LV', 'Riga', 371, 'EUR', '€', 'https://restcountries.eu/data/lva.svg'],
                ['Lebanon', 'LB', 'Beirut', 961, 'LBP', 'ل.ل', 'https://restcountries.eu/data/lbn.svg'],
                ['Lesotho', 'LS', 'Maseru', 266, 'LSL', 'L', 'https://restcountries.eu/data/lso.svg'],
                ['Liberia', 'LR', 'Monrovia', 231, 'LRD', '$', 'https://restcountries.eu/data/lbr.svg'],
                ['Libya', 'LY', 'Tripoli', 218, 'LYD', 'ل.د', 'https://restcountries.eu/data/lby.svg'],
                ['Liechtenstein', 'LI', 'Vaduz', 423, 'CHF', 'Fr', 'https://restcountries.eu/data/lie.svg'],
                ['Lithuania', 'LT', 'Vilnius', 370, 'EUR', '€', 'https://restcountries.eu/data/ltu.svg'],
                ['Luxembourg', 'LU', 'Luxembourg', 352, 'EUR', '€', 'https://restcountries.eu/data/lux.svg'],
                ['Macao', 'MO', '', 853, 'MOP', 'P', 'https://restcountries.eu/data/mac.svg'],
                ['Macedonia', 'MK', 'Skopje', 389, 'MKD', 'ден', 'https://restcountries.eu/data/mkd.svg'],
                ['Madagascar', 'MG', 'Antananarivo', 261, 'MGA', 'Ar', 'https://restcountries.eu/data/mdg.svg'],
                ['Malawi', 'MW', 'Lilongwe', 265, 'MWK', 'MK', 'https://restcountries.eu/data/mwi.svg'],
                ['Malaysia', 'MY', 'Kuala Lumpur', 60, 'MYR', 'RM', 'https://restcountries.eu/data/mys.svg'],
                ['Maldives', 'MV', 'Malé', 960, 'MVR', '.ރ', 'https://restcountries.eu/data/mdv.svg'],
                ['Mali', 'ML', 'Bamako', 223, 'XOF', 'Fr', 'https://restcountries.eu/data/mli.svg'],
                ['Malta', 'MT', 'Valletta', 356, 'EUR', '€', 'https://restcountries.eu/data/mlt.svg'],
                ['Marshall Islands', 'MH', 'Majuro', 692, 'USD', '$', 'https://restcountries.eu/data/mhl.svg'],
                ['Martinique', 'MQ', 'Fort-de-France', 596, 'EUR', '€', 'https://restcountries.eu/data/mtq.svg'],
                ['Mauritania', 'MR', 'Nouakchott', 222, 'MRO', 'UM', 'https://restcountries.eu/data/mrt.svg'],
                ['Mauritius', 'MU', 'Port Louis', 230, 'MUR', '₨', 'https://restcountries.eu/data/mus.svg'],
                ['Mayotte', 'YT', 'Mamoudzou', 262, 'EUR', '€', 'https://restcountries.eu/data/myt.svg'],
                ['Mexico', 'MX', 'Mexico City', 52, 'MXN', '$', 'https://restcountries.eu/data/mex.svg'],
                ['Micronesia', 'FM', 'Palikir', 691, NULL, '$', 'https://restcountries.eu/data/fsm.svg'],
                ['Moldova', 'MD', 'Chișinău', 373, 'MDL', 'L', 'https://restcountries.eu/data/mda.svg'],
                ['Monaco', 'MC', 'Monaco', 377, 'EUR', '€', 'https://restcountries.eu/data/mco.svg'],
                ['Mongolia', 'MN', 'Ulan Bator', 976, 'MNT', '₮', 'https://restcountries.eu/data/mng.svg'],
                ['Montenegro', 'ME', 'Podgorica', 382, 'EUR', '€', 'https://restcountries.eu/data/mne.svg'],
                ['Montserrat', 'MS', 'Plymouth', 1664, 'XCD', '$', 'https://restcountries.eu/data/msr.svg'],
                ['Morocco', 'MA', 'Rabat', 212, 'MAD', 'د.م.', 'https://restcountries.eu/data/mar.svg'],
                ['Mozambique', 'MZ', 'Maputo', 258, 'MZN', 'MT', 'https://restcountries.eu/data/moz.svg'],
                ['Myanmar', 'MM', 'Naypyidaw', 95, 'MMK', 'Ks', 'https://restcountries.eu/data/mmr.svg'],
                ['Namibia', 'NA', 'Windhoek', 264, 'NAD', '$', 'https://restcountries.eu/data/nam.svg'],
                ['Nauru', 'NR', 'Yaren', 674, 'AUD', '$', 'https://restcountries.eu/data/nru.svg'],
                ['Nepal', 'NP', 'Kathmandu', 977, 'NPR', '₨', 'https://restcountries.eu/data/npl.svg'],
                ['Netherlands', 'NL', 'Amsterdam', 31, 'EUR', '€', 'https://restcountries.eu/data/nld.svg'],
                ['New Caledonia', 'NC', 'Nouméa', 687, 'XPF', 'Fr', 'https://restcountries.eu/data/ncl.svg'],
                ['New Zealand', 'NZ', 'Wellington', 64, 'NZD', '$', 'https://restcountries.eu/data/nzl.svg'],
                ['Nicaragua', 'NI', 'Managua', 505, 'NIO', 'C$', 'https://restcountries.eu/data/nic.svg'],
                ['Niger', 'NE', 'Niamey', 227, 'XOF', 'Fr', 'https://restcountries.eu/data/ner.svg'],
                ['Nigeria', 'NG', 'Abuja', 234, 'NGN', '₦', 'https://restcountries.eu/data/nga.svg'],
                ['Niue', 'NU', 'Alofi', 683, 'NZD', '$', 'https://restcountries.eu/data/niu.svg'],
                ['Norfolk Island', 'NF', 'Kingston', 672, 'AUD', '$', 'https://restcountries.eu/data/nfk.svg'],
                ['Korea', 'KP', 'Pyongyang', 850, 'KPW', '₩', 'https://restcountries.eu/data/prk.svg'],
                ['Northern Mariana Islands', 'MP', 'Saipan', 1670, 'USD', '$', 'https://restcountries.eu/data/mnp.svg'],
                ['Norway', 'NO', 'Oslo', 47, 'NOK', 'kr', 'https://restcountries.eu/data/nor.svg'],
                ['Oman', 'OM', 'Muscat', 968, 'OMR', 'ر.ع.', 'https://restcountries.eu/data/omn.svg'],
                ['Pakistan', 'PK', 'Islamabad', 92, 'PKR', '₨', 'https://restcountries.eu/data/pak.svg'],
                ['Palau', 'PW', 'Ngerulmud', 680, '(none)', '$', 'https://restcountries.eu/data/plw.svg'],
                ['Palestine, State of', 'PS', 'Ramallah', 970, 'ILS', '₪', 'https://restcountries.eu/data/pse.svg'],
                ['Panama', 'PA', 'Panama City', 507, 'PAB', 'B/.', 'https://restcountries.eu/data/pan.svg'],
                ['Papua New Guinea', 'PG', 'Port Moresby', 675, 'PGK', 'K', 'https://restcountries.eu/data/png.svg'],
                ['Paraguay', 'PY', 'Asunción', 595, 'PYG', '₲', 'https://restcountries.eu/data/pry.svg'],
                ['Peru', 'PE', 'Lima', 51, 'PEN', 'S/.', 'https://restcountries.eu/data/per.svg'],
                ['Philippines', 'PH', 'Manila', 63, 'PHP', '₱', 'https://restcountries.eu/data/phl.svg'],
                ['Pitcairn', 'PN', 'Adamstown', 64, 'NZD', '$', 'https://restcountries.eu/data/pcn.svg'],
                ['Poland', 'PL', 'Warsaw', 48, 'PLN', 'zł', 'https://restcountries.eu/data/pol.svg'],
                ['Portugal', 'PT', 'Lisbon', 351, 'EUR', '€', 'https://restcountries.eu/data/prt.svg'],
                ['Puerto Rico', 'PR', 'San Juan', 1787, 'USD', '$', 'https://restcountries.eu/data/pri.svg'],
                ['Qatar', 'QA', 'Doha', 974, 'QAR', 'ر.ق', 'https://restcountries.eu/data/qat.svg'],
                ['Republic of Kosovo', 'XK', 'Pristina', 383, 'EUR', '€', 'https://restcountries.eu/data/kos.svg'],
                ['Réunion', 'RE', 'Saint-Denis', 262, 'EUR', '€', 'https://restcountries.eu/data/reu.svg'],
                ['Romania', 'RO', 'Bucharest', 40, 'RON', 'lei', 'https://restcountries.eu/data/rou.svg'],
                ['Russian Federation', 'RU', 'Moscow', 7, 'RUB', '₽', 'https://restcountries.eu/data/rus.svg'],
                ['Rwanda', 'RW', 'Kigali', 250, 'RWF', 'Fr', 'https://restcountries.eu/data/rwa.svg'],
                ['Saint Barthélemy', 'BL', 'Gustavia', 590, 'EUR', '€', 'https://restcountries.eu/data/blm.svg'],
                ['Saint Helena', 'SH', 'Jamestown', 290, 'SHP', '£', 'https://restcountries.eu/data/shn.svg'],
                ['Saint Kitts and Nevis', 'KN', 'Basseterre', 1869, 'XCD', '$', 'https://restcountries.eu/data/kna.svg'],
                ['Saint Lucia', 'LC', 'Castries', 1758, 'XCD', '$', 'https://restcountries.eu/data/lca.svg'],
                ['Saint Martin (French part)', 'MF', 'Marigot', 590, 'EUR', '€', 'https://restcountries.eu/data/maf.svg'],
                ['Saint Pierre and Miquelon', 'PM', 'Saint-Pierre', 508, 'EUR', '€', 'https://restcountries.eu/data/spm.svg'],
                ['Saint Vincent and the Grenadines', 'VC', 'Kingstown', 1784, 'XCD', '$', 'https://restcountries.eu/data/vct.svg'],
                ['Samoa', 'WS', 'Apia', 685, 'WST', 'T', 'https://restcountries.eu/data/wsm.svg'],
                ['San Marino', 'SM', 'City of San Marino', 378, 'EUR', '€', 'https://restcountries.eu/data/smr.svg'],
                ['Sao Tome and Principe', 'ST', 'São Tomé', 239, 'STD', 'Db', 'https://restcountries.eu/data/stp.svg'],
                ['Saudi Arabia', 'SA', 'Riyadh', 966, 'SAR', 'ر.س', 'https://restcountries.eu/data/sau.svg'],
                ['Senegal', 'SN', 'Dakar', 221, 'XOF', 'Fr', 'https://restcountries.eu/data/sen.svg'],
                ['Serbia', 'RS', 'Belgrade', 381, 'RSD', 'дин.', 'https://restcountries.eu/data/srb.svg'],
                ['Seychelles', 'SC', 'Victoria', 248, 'SCR', '₨', 'https://restcountries.eu/data/syc.svg'],
                ['Sierra Leone', 'SL', 'Freetown', 232, 'SLL', 'Le', 'https://restcountries.eu/data/sle.svg'],
                ['Singapore', 'SG', 'Singapore', 65, 'BND', '$', 'https://restcountries.eu/data/sgp.svg'],
                ['Sint Maarten', 'SX', 'Philipsburg', 1721, 'ANG', 'ƒ', 'https://restcountries.eu/data/sxm.svg'],
                ['Slovakia', 'SK', 'Bratislava', 421, 'EUR', '€', 'https://restcountries.eu/data/svk.svg'],
                ['Slovenia', 'SI', 'Ljubljana', 386, 'EUR', '€', 'https://restcountries.eu/data/svn.svg'],
                ['Solomon Islands', 'SB', 'Honiara', 677, 'SBD', '$', 'https://restcountries.eu/data/slb.svg'],
                ['Somalia', 'SO', 'Mogadishu', 252, 'SOS', 'Sh', 'https://restcountries.eu/data/som.svg'],
                ['South Africa', 'ZA', 'Pretoria', 27, 'ZAR', 'R', 'https://restcountries.eu/data/zaf.svg'],
                ['South Georgia', 'GS', 'King Edward Point', 500, 'GBP', '£', 'https://restcountries.eu/data/sgs.svg'],
                ['Korea', 'KR', 'Seoul', 82, 'KRW', '₩', 'https://restcountries.eu/data/kor.svg'],
                ['South Sudan', 'SS', 'Juba', 211, 'SSP', '£', 'https://restcountries.eu/data/ssd.svg'],
                ['Spain', 'ES', 'Madrid', 34, 'EUR', '€', 'https://restcountries.eu/data/esp.svg'],
                ['Sri Lanka', 'LK', 'Colombo', 94, 'LKR', 'Rs', 'https://restcountries.eu/data/lka.svg'],
                ['Sudan', 'SD', 'Khartoum', 249, 'SDG', 'ج.س.', 'https://restcountries.eu/data/sdn.svg'],
                ['Suriname', 'SR', 'Paramaribo', 597, 'SRD', '$', 'https://restcountries.eu/data/sur.svg'],
                ['Svalbard and Jan Mayen', 'SJ', 'Longyearbyen', 4779, 'NOK', 'kr', 'https://restcountries.eu/data/sjm.svg'],
                ['Swaziland', 'SZ', 'Lobamba', 268, 'SZL', 'L', 'https://restcountries.eu/data/swz.svg'],
                ['Sweden', 'SE', 'Stockholm', 46, 'SEK', 'kr', 'https://restcountries.eu/data/swe.svg'],
                ['Switzerland', 'CH', 'Bern', 41, 'CHF', 'Fr', 'https://restcountries.eu/data/che.svg'],
                ['Syrian Arab Republic', 'SY', 'Damascus', 963, 'SYP', '£', 'https://restcountries.eu/data/syr.svg'],
                ['Taiwan', 'TW', 'Taipei', 886, 'TWD', '$', 'https://restcountries.eu/data/twn.svg'],
                ['Tajikistan', 'TJ', 'Dushanbe', 992, 'TJS', 'ЅМ', 'https://restcountries.eu/data/tjk.svg'],
                ['Tanzania', 'TZ', 'Dodoma', 255, 'TZS', 'Sh', 'https://restcountries.eu/data/tza.svg'],
                ['Thailand', 'TH', 'Bangkok', 66, 'THB', '฿', 'https://restcountries.eu/data/tha.svg'],
                ['Timor-Leste', 'TL', 'Dili', 670, 'USD', '$', 'https://restcountries.eu/data/tls.svg'],
                ['Togo', 'TG', 'Lomé', 228, 'XOF', 'Fr', 'https://restcountries.eu/data/tgo.svg'],
                ['Tokelau', 'TK', 'Fakaofo', 690, 'NZD', '$', 'https://restcountries.eu/data/tkl.svg'],
                ['Tonga', 'TO', 'Nuku\'alofa', 676, 'TOP', 'T$', 'https://restcountries.eu/data/ton.svg'],
                ['Trinidad and Tobago', 'TT', 'Port of Spain', 1868, 'TTD', '$', 'https://restcountries.eu/data/tto.svg'],
                ['Tunisia', 'TN', 'Tunis', 216, 'TND', 'د.ت', 'https://restcountries.eu/data/tun.svg'],
                ['Turkey', 'TR', 'Ankara', 90, 'TRY', NULL, 'https://restcountries.eu/data/tur.svg'],
                ['Turkmenistan', 'TM', 'Ashgabat', 993, 'TMT', 'm', 'https://restcountries.eu/data/tkm.svg'],
                ['Turks and Caicos Islands', 'TC', 'Cockburn Town', 1649, 'USD', '$', 'https://restcountries.eu/data/tca.svg'],
                ['Tuvalu', 'TV', 'Funafuti', 688, 'AUD', '$', 'https://restcountries.eu/data/tuv.svg'],
                ['Uganda', 'UG', 'Kampala', 256, 'UGX', 'Sh', 'https://restcountries.eu/data/uga.svg'],
                ['Ukraine', 'UA', 'Kiev', 380, 'UAH', '₴', 'https://restcountries.eu/data/ukr.svg'],
                ['United Arab Emirates', 'AE', 'Abu Dhabi', 971, 'AED', 'د.إ', 'https://restcountries.eu/data/are.svg'],
                ['United Kingdom', 'GB', 'London', 44, 'GBP', '£', 'https://restcountries.eu/data/gbr.svg'],
                ['United States', 'US', 'Washington, D.C.', 1, 'USD', '$', 'https://restcountries.eu/data/usa.svg'],
                ['Uruguay', 'UY', 'Montevideo', 598, 'UYU', '$', 'https://restcountries.eu/data/ury.svg'],
                ['Uzbekistan', 'UZ', 'Tashkent', 998, 'UZS', NULL, 'https://restcountries.eu/data/uzb.svg'],
                ['Vanuatu', 'VU', 'Port Vila', 678, 'VUV', 'Vt', 'https://restcountries.eu/data/vut.svg'],
                ['Venezuela', 'VE', 'Caracas', 58, 'VEF', 'Bs F', 'https://restcountries.eu/data/ven.svg'],
                ['Viet Nam', 'VN', 'Hanoi', 84, 'VND', '₫', 'https://restcountries.eu/data/vnm.svg'],
                ['Wallis and Futuna', 'WF', 'Mata-Utu', 681, 'XPF', 'Fr', 'https://restcountries.eu/data/wlf.svg'],
                ['Western Sahara', 'EH', 'El Aaiún', 212, 'MAD', 'د.م.', 'https://restcountries.eu/data/esh.svg'],
                ['Yemen', 'YE', 'Sana\'a', 967, 'YER', '﷼', 'https://restcountries.eu/data/yem.svg'],
                ['Zambia', 'ZM', 'Lusaka', 260, 'ZMW', 'ZK', 'https://restcountries.eu/data/zmb.svg'],
                ['Zimbabwe', 'ZW', 'Harare', 263, 'BWP', 'P', 'https://restcountries.eu/data/zwe.svg'],
            ]);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable('{{%country}}');
    }
}
