<?php

use yii\db\Migration;

/**
 * Class m180214_034117_insert_channel_attributes_to_connection_attribution
 */
class m180214_034117_insert_channel_attributes_to_connection_attribution extends Migration
{
    /**
     * @inheritdoc
     */
    public function safeUp()
    {
        $this->batchInsert('{{%connection_attribution}}', ['name', 'label', 'description', 'connection_id'], [

            ['name',NULL,NULL,'30'],
            ['SellerSku',NULL,NULL,'30'],
            ['Url',NULL,NULL,'30'],
            ['short_description',NULL,NULL,'30'],
            ['brand',NULL,NULL,'30'],
            ['condition',NULL,NULL,'30'],
            ['package_weight',NULL,NULL,'30'],
            ['package_length',NULL,NULL,'30'],
            ['package_height',NULL,NULL,'30'],
            ['package_width',NULL,NULL,'30'],
            ['package_content',NULL,NULL,'30'],
            ['Available',NULL,NULL,'30'],
            ['price',NULL,NULL,'30'],
            ['special_price',NULL,NULL,'30'],
            ['special_from_date',NULL,NULL,'30'],
            ['warranty_type',NULL,NULL,'30'],

            ['name',NULL,NULL,'31'],
            ['SellerSku',NULL,NULL,'31'],
            ['Url',NULL,NULL,'31'],
            ['short_description',NULL,NULL,'31'],
            ['brand',NULL,NULL,'31'],
            ['condition',NULL,NULL,'31'],
            ['package_weight',NULL,NULL,'31'],
            ['package_length',NULL,NULL,'31'],
            ['package_height',NULL,NULL,'31'],
            ['package_width',NULL,NULL,'31'],
            ['package_content',NULL,NULL,'31'],
            ['Available',NULL,NULL,'31'],
            ['price',NULL,NULL,'31'],
            ['special_price',NULL,NULL,'31'],
            ['special_from_date',NULL,NULL,'31'],
            ['warranty_type',NULL,NULL,'31'],

            ['name',NULL,NULL,'32'],
            ['SellerSku',NULL,NULL,'32'],
            ['Url',NULL,NULL,'32'],
            ['short_description',NULL,NULL,'32'],
            ['brand',NULL,NULL,'32'],
            ['condition',NULL,NULL,'32'],
            ['package_weight',NULL,NULL,'32'],
            ['package_length',NULL,NULL,'32'],
            ['package_height',NULL,NULL,'32'],
            ['package_width',NULL,NULL,'32'],
            ['package_content',NULL,NULL,'32'],
            ['Available',NULL,NULL,'32'],
            ['price',NULL,NULL,'32'],
            ['special_price',NULL,NULL,'32'],
            ['special_from_date',NULL,NULL,'32'],
            ['warranty_type',NULL,NULL,'32'],

            ['name',NULL,NULL,'33'],
            ['SellerSku',NULL,NULL,'33'],
            ['Url',NULL,NULL,'33'],
            ['short_description',NULL,NULL,'33'],
            ['brand',NULL,NULL,'33'],
            ['condition',NULL,NULL,'33'],
            ['package_weight',NULL,NULL,'33'],
            ['package_length',NULL,NULL,'33'],
            ['package_height',NULL,NULL,'33'],
            ['package_width',NULL,NULL,'33'],
            ['package_content',NULL,NULL,'33'],
            ['Available',NULL,NULL,'33'],
            ['price',NULL,NULL,'33'],
            ['special_price',NULL,NULL,'33'],
            ['special_from_date',NULL,NULL,'33'],
            ['warranty_type',NULL,NULL,'33'],

            ['name',NULL,NULL,'34'],
            ['SellerSku',NULL,NULL,'34'],
            ['Url',NULL,NULL,'34'],
            ['short_description',NULL,NULL,'34'],
            ['brand',NULL,NULL,'34'],
            ['condition',NULL,NULL,'34'],
            ['package_weight',NULL,NULL,'34'],
            ['package_length',NULL,NULL,'34'],
            ['package_height',NULL,NULL,'34'],
            ['package_width',NULL,NULL,'34'],
            ['package_content',NULL,NULL,'34'],
            ['Available',NULL,NULL,'34'],
            ['price',NULL,NULL,'34'],
            ['special_price',NULL,NULL,'34'],
            ['special_from_date',NULL,NULL,'34'],
            ['warranty_type',NULL,NULL,'34'],

            ['name',NULL,NULL,'35'],
            ['SellerSku',NULL,NULL,'35'],
            ['Url',NULL,NULL,'35'],
            ['short_description',NULL,NULL,'35'],
            ['brand',NULL,NULL,'35'],
            ['condition',NULL,NULL,'35'],
            ['package_weight',NULL,NULL,'35'],
            ['package_length',NULL,NULL,'35'],
            ['package_height',NULL,NULL,'35'],
            ['package_width',NULL,NULL,'35'],
            ['package_content',NULL,NULL,'35'],
            ['Available',NULL,NULL,'35'],
            ['price',NULL,NULL,'35'],
            ['special_price',NULL,NULL,'35'],
            ['special_from_date',NULL,NULL,'35'],
            ['warranty_type',NULL,NULL,'35'],

            ['item-name',NULL,NULL,'14'],
            ['seller-sku',NULL,NULL,'14'],
            ['image-url',NULL,NULL,'14'],
            ['item-description',NULL,NULL,'14'],
            ['Brand',NULL,NULL,'14'],
            ['medium_image',NULL,NULL,'14'],
            ['small_image',NULL,NULL,'14'],
            ['large_image',NULL,NULL,'14'],
            ['Width',NULL,NULL,'14'],
            ['Length',NULL,NULL,'14'],
            ['Height',NULL,NULL,'14'],
            ['Weight',NULL,NULL,'14'],
            ['PackageDimensions',NULL,NULL,'14'],
            ['ItemDimensions',NULL,NULL,'14'],
            ['ASIN',NULL,NULL,'14'],
            ['PackageQuantity',NULL,NULL,'14'],
            ['ListPrice',NULL,NULL,'14'],
            ['open-date',NULL,NULL,'14'],
            ['quantity',NULL,NULL,'14'],
            ['price',NULL,NULL,'14'],
            ['status',NULL,NULL,'14'],
            ['product-id',NULL,NULL,'14'],
            ['product-id-type',NULL,NULL,'14'],

            ['item-name',NULL,NULL,'15'],
            ['seller-sku',NULL,NULL,'15'],
            ['image-url',NULL,NULL,'15'],
            ['item-description',NULL,NULL,'15'],
            ['Brand',NULL,NULL,'15'],
            ['medium_image',NULL,NULL,'15'],
            ['small_image',NULL,NULL,'15'],
            ['large_image',NULL,NULL,'15'],
            ['Width',NULL,NULL,'15'],
            ['Length',NULL,NULL,'15'],
            ['Height',NULL,NULL,'15'],
            ['Weight',NULL,NULL,'15'],
            ['PackageDimensions',NULL,NULL,'15'],
            ['ItemDimensions',NULL,NULL,'15'],
            ['ASIN',NULL,NULL,'15'],
            ['PackageQuantity',NULL,NULL,'15'],
            ['ListPrice',NULL,NULL,'15'],
            ['open-date',NULL,NULL,'15'],
            ['quantity',NULL,NULL,'15'],
            ['price',NULL,NULL,'15'],
            ['status',NULL,NULL,'15'],
            ['product-id',NULL,NULL,'15'],
            ['product-id-type',NULL,NULL,'15'],

            ['item-name',NULL,NULL,'16'],
            ['seller-sku',NULL,NULL,'16'],
            ['image-url',NULL,NULL,'16'],
            ['item-description',NULL,NULL,'16'],
            ['Brand',NULL,NULL,'16'],
            ['medium_image',NULL,NULL,'16'],
            ['small_image',NULL,NULL,'16'],
            ['large_image',NULL,NULL,'16'],
            ['Width',NULL,NULL,'16'],
            ['Length',NULL,NULL,'16'],
            ['Height',NULL,NULL,'16'],
            ['Weight',NULL,NULL,'16'],
            ['PackageDimensions',NULL,NULL,'16'],
            ['ItemDimensions',NULL,NULL,'16'],
            ['ASIN',NULL,NULL,'16'],
            ['PackageQuantity',NULL,NULL,'16'],
            ['ListPrice',NULL,NULL,'16'],
            ['open-date',NULL,NULL,'16'],
            ['quantity',NULL,NULL,'16'],
            ['price',NULL,NULL,'16'],
            ['status',NULL,NULL,'16'],
            ['product-id',NULL,NULL,'16'],
            ['product-id-type',NULL,NULL,'16'],

            ['item-name',NULL,NULL,'17'],
            ['seller-sku',NULL,NULL,'17'],
            ['image-url',NULL,NULL,'17'],
            ['item-description',NULL,NULL,'17'],
            ['Brand',NULL,NULL,'17'],
            ['medium_image',NULL,NULL,'17'],
            ['small_image',NULL,NULL,'17'],
            ['large_image',NULL,NULL,'17'],
            ['Width',NULL,NULL,'17'],
            ['Length',NULL,NULL,'17'],
            ['Height',NULL,NULL,'17'],
            ['Weight',NULL,NULL,'17'],
            ['PackageDimensions',NULL,NULL,'17'],
            ['ItemDimensions',NULL,NULL,'17'],
            ['ASIN',NULL,NULL,'17'],
            ['PackageQuantity',NULL,NULL,'14'],
            ['ListPrice',NULL,NULL,'17'],
            ['open-date',NULL,NULL,'17'],
            ['quantity',NULL,NULL,'17'],
            ['price',NULL,NULL,'17'],
            ['status',NULL,NULL,'17'],
            ['product-id',NULL,NULL,'17'],
            ['product-id-type',NULL,NULL,'17'],

            ['item-name',NULL,NULL,'18'],
            ['seller-sku',NULL,NULL,'18'],
            ['image-url',NULL,NULL,'18'],
            ['item-description',NULL,NULL,'18'],
            ['Brand',NULL,NULL,'18'],
            ['medium_image',NULL,NULL,'18'],
            ['small_image',NULL,NULL,'18'],
            ['large_image',NULL,NULL,'18'],
            ['Width',NULL,NULL,'18'],
            ['Length',NULL,NULL,'18'],
            ['Height',NULL,NULL,'18'],
            ['Weight',NULL,NULL,'18'],
            ['PackageDimensions',NULL,NULL,'18'],
            ['ItemDimensions',NULL,NULL,'18'],
            ['ASIN',NULL,NULL,'18'],
            ['PackageQuantity',NULL,NULL,'18'],
            ['ListPrice',NULL,NULL,'18'],
            ['open-date',NULL,NULL,'18'],
            ['quantity',NULL,NULL,'18'],
            ['price',NULL,NULL,'18'],
            ['status',NULL,NULL,'18'],
            ['product-id',NULL,NULL,'18'],
            ['product-id-type',NULL,NULL,'18'],

            ['item-name',NULL,NULL,'19'],
            ['seller-sku',NULL,NULL,'19'],
            ['image-url',NULL,NULL,'19'],
            ['item-description',NULL,NULL,'19'],
            ['Brand',NULL,NULL,'19'],
            ['medium_image',NULL,NULL,'19'],
            ['small_image',NULL,NULL,'19'],
            ['large_image',NULL,NULL,'19'],
            ['Width',NULL,NULL,'19'],
            ['Length',NULL,NULL,'19'],
            ['Height',NULL,NULL,'19'],
            ['Weight',NULL,NULL,'19'],
            ['PackageDimensions',NULL,NULL,'19'],
            ['ItemDimensions',NULL,NULL,'19'],
            ['ASIN',NULL,NULL,'19'],
            ['PackageQuantity',NULL,NULL,'19'],
            ['ListPrice',NULL,NULL,'19'],
            ['open-date',NULL,NULL,'19'],
            ['quantity',NULL,NULL,'19'],
            ['price',NULL,NULL,'19'],
            ['status',NULL,NULL,'19'],
            ['product-id',NULL,NULL,'19'],
            ['product-id-type',NULL,NULL,'19'],

            ['item-name',NULL,NULL,'20'],
            ['seller-sku',NULL,NULL,'20'],
            ['image-url',NULL,NULL,'20'],
            ['item-description',NULL,NULL,'20'],
            ['Brand',NULL,NULL,'20'],
            ['medium_image',NULL,NULL,'20'],
            ['small_image',NULL,NULL,'20'],
            ['large_image',NULL,NULL,'20'],
            ['Width',NULL,NULL,'20'],
            ['Length',NULL,NULL,'20'],
            ['Height',NULL,NULL,'20'],
            ['Weight',NULL,NULL,'20'],
            ['PackageDimensions',NULL,NULL,'20'],
            ['ItemDimensions',NULL,NULL,'20'],
            ['ASIN',NULL,NULL,'20'],
            ['PackageQuantity',NULL,NULL,'20'],
            ['ListPrice',NULL,NULL,'20'],
            ['open-date',NULL,NULL,'20'],
            ['quantity',NULL,NULL,'20'],
            ['price',NULL,NULL,'20'],
            ['status',NULL,NULL,'20'],
            ['product-id',NULL,NULL,'20'],
            ['product-id-type',NULL,NULL,'20'],

            ['item-name',NULL,NULL,'21'],
            ['seller-sku',NULL,NULL,'21'],
            ['image-url',NULL,NULL,'21'],
            ['item-description',NULL,NULL,'21'],
            ['Brand',NULL,NULL,'21'],
            ['medium_image',NULL,NULL,'21'],
            ['small_image',NULL,NULL,'21'],
            ['large_image',NULL,NULL,'21'],
            ['Width',NULL,NULL,'21'],
            ['Length',NULL,NULL,'21'],
            ['Height',NULL,NULL,'21'],
            ['Weight',NULL,NULL,'21'],
            ['PackageDimensions',NULL,NULL,'21'],
            ['ItemDimensions',NULL,NULL,'21'],
            ['ASIN',NULL,NULL,'21'],
            ['PackageQuantity',NULL,NULL,'21'],
            ['ListPrice',NULL,NULL,'21'],
            ['open-date',NULL,NULL,'21'],
            ['quantity',NULL,NULL,'21'],
            ['price',NULL,NULL,'21'],
            ['status',NULL,NULL,'21'],
            ['product-id',NULL,NULL,'21'],
            ['product-id-type',NULL,NULL,'21'],

            ['item-name',NULL,NULL,'22'],
            ['seller-sku',NULL,NULL,'22'],
            ['image-url',NULL,NULL,'22'],
            ['item-description',NULL,NULL,'22'],
            ['Brand',NULL,NULL,'22'],
            ['medium_image',NULL,NULL,'22'],
            ['small_image',NULL,NULL,'22'],
            ['large_image',NULL,NULL,'22'],
            ['Width',NULL,NULL,'22'],
            ['Length',NULL,NULL,'22'],
            ['Height',NULL,NULL,'22'],
            ['Weight',NULL,NULL,'22'],
            ['PackageDimensions',NULL,NULL,'22'],
            ['ItemDimensions',NULL,NULL,'22'],
            ['ASIN',NULL,NULL,'22'],
            ['PackageQuantity',NULL,NULL,'22'],
            ['ListPrice',NULL,NULL,'22'],
            ['open-date',NULL,NULL,'22'],
            ['quantity',NULL,NULL,'22'],
            ['price',NULL,NULL,'22'],
            ['status',NULL,NULL,'22'],
            ['product-id',NULL,NULL,'22'],
            ['product-id-type',NULL,NULL,'22'],

            ['Website Short Title',NULL,NULL,'58'],
            ['Seller Part #',NULL,NULL,'58'],
            ['image_url',NULL,NULL,'58'],
            ['UPC / ISBN',NULL,NULL,'58'],
            ['Product Description',NULL,NULL,'58'],
            ['Manufacturer',NULL,NULL,'58'],
            ['Item Condition',NULL,NULL,'58'],
            ['Item Weight',NULL,NULL,'58'],
            ['Item Length',NULL,NULL,'58'],
            ['Item Height',NULL,NULL,'58'],
            ['Item Width',NULL,NULL,'58'],
            ['Inventory',NULL,NULL,'58'],
            ['Currency',NULL,NULL,'58'],
            ['Country Of Origin',NULL,NULL,'58'],
            ['Selling Price',NULL,NULL,'58'],
            ['Currency',NULL,NULL,'58'],
            ['NE Item #',NULL,NULL,'58'],
            ['SubCategoryID',NULL,NULL,'58'],

            ['Website Short Title',NULL,NULL,'59'],
            ['Seller Part #',NULL,NULL,'59'],
            ['image_url',NULL,NULL,'59'],
            ['UPC / ISBN',NULL,NULL,'59'],
            ['Product Description',NULL,NULL,'59'],
            ['Manufacturer',NULL,NULL,'59'],
            ['Item Condition',NULL,NULL,'59'],
            ['Item Weight',NULL,NULL,'59'],
            ['Item Length',NULL,NULL,'59'],
            ['Item Height',NULL,NULL,'59'],
            ['Item Width',NULL,NULL,'59'],
            ['Inventory',NULL,NULL,'59'],
            ['Currency',NULL,NULL,'59'],
            ['Country Of Origin',NULL,NULL,'59'],
            ['Selling Price',NULL,NULL,'59'],
            ['Currency',NULL,NULL,'59'],
            ['NE Item #',NULL,NULL,'59'],
            ['SubCategoryID',NULL,NULL,'59'],

            ['Website Short Title',NULL,NULL,'60'],
            ['Seller Part #',NULL,NULL,'60'],
            ['image_url',NULL,NULL,'60'],
            ['UPC / ISBN',NULL,NULL,'60'],
            ['Product Description',NULL,NULL,'60'],
            ['Manufacturer',NULL,NULL,'60'],
            ['Item Condition',NULL,NULL,'60'],
            ['Item Weight',NULL,NULL,'60'],
            ['Item Length',NULL,NULL,'60'],
            ['Item Height',NULL,NULL,'60'],
            ['Item Width',NULL,NULL,'60'],
            ['Inventory',NULL,NULL,'60'],
            ['Currency',NULL,NULL,'60'],
            ['Country Of Origin',NULL,NULL,'60'],
            ['Selling Price',NULL,NULL,'60'],
            ['Currency',NULL,NULL,'60'],
            ['NE Item #',NULL,NULL,'60'],
            ['SubCategoryID',NULL,NULL,'60'],

            ['title',NULL,NULL,'52'],
            ['sku',NULL,NULL,'52'],
            ['thumbnail',NULL,NULL,'52'],
            ['description',NULL,NULL,'52'],
            ['weight',NULL,NULL,'52'],
            ['unit',NULL,NULL,'52'],
            ['stock',NULL,NULL,'52'],
            ['price',NULL,NULL,'52'],
            ['salesPrice',NULL,NULL,'52'],
            ['_id',NULL,NULL,'52'],
            ['categoryGroupId',NULL,NULL,'52'],
            ['created',NULL,NULL,'52'],
            ['modified',NULL,NULL,'52'],
            ['barcode',NULL,NULL,'52'],
            ['sku_id',NULL,NULL,'52'],
            ['product_code',NULL,NULL,'52'],
            ['name',NULL,NULL,'52'],
            ['icon_url',NULL,NULL,'52'],
            ['detail_html',NULL,NULL,'52'],
            ['ori_price',NULL,NULL,'52'],

            ['title',NULL,NULL,'53'],
            ['sku',NULL,NULL,'53'],
            ['thumbnail',NULL,NULL,'53'],
            ['description',NULL,NULL,'53'],
            ['weight',NULL,NULL,'53'],
            ['unit',NULL,NULL,'53'],
            ['stock',NULL,NULL,'53'],
            ['price',NULL,NULL,'53'],
            ['salesPrice',NULL,NULL,'53'],
            ['_id',NULL,NULL,'53'],
            ['categoryGroupId',NULL,NULL,'53'],
            ['created',NULL,NULL,'53'],
            ['modified',NULL,NULL,'53'],
            ['barcode',NULL,NULL,'53'],
            ['sku_id',NULL,NULL,'53'],
            ['product_code',NULL,NULL,'53'],
            ['name',NULL,NULL,'53'],
            ['icon_url',NULL,NULL,'53'],
            ['detail_html',NULL,NULL,'53'],
            ['ori_price',NULL,NULL,'53'],

            ['name',NULL,NULL,'63'],
            ['sku_value',NULL,NULL,'63'],
            ['image_url',NULL,NULL,'63'],
            ['upc',NULL,NULL,'63'],
            ['description',NULL,NULL,'63'],
            ['currency',NULL,NULL,'63'],
            ['price_value',NULL,NULL,'63'],
            ['id',NULL,NULL,'63'],
            ['created_at',NULL,NULL,'63'],
            ['updated_at',NULL,NULL,'63'],
            ['product_type',NULL,NULL,'63'],
            ['category_id',NULL,NULL,'63'],
            ['amount',NULL,NULL,'63'],
            ['category_id',NULL,NULL,'63'],
            ['quantity_on_hand',NULL,NULL,'63']

        ]);
    }

    /**
     * @inheritdoc
     */
    public function safeDown()
    {
        echo "m180214_034117_insert_channel_attributes_to_connection_attribution cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m180214_034117_insert_channel_attributes_to_connection_attribution cannot be reverted.\n";

        return false;
    }
    */
}
